# Generated by Django 5.0.4 on 2024-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(default='', max_length=50)),
                ('content_image', models.ImageField(upload_to='')),
                ('content_title', models.CharField(max_length=100)),
                ('content_description', models.TextField(default='')),
                ('content_id', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
