# Generated by Django 5.0.4 on 2024-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('profile_pic', models.ImageField(default='user.png', upload_to='profile_pics/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
