# Generated by Django 5.0.4 on 2024-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_id',
            field=models.TextField(default=''),
        ),
    ]
