# Generated by Django 5.0.4 on 2024-04-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
