# Generated by Django 5.0.4 on 2024-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to='profile_pics/'),
        ),
    ]
