# Generated by Django 5.0.4 on 2024-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content_id',
            field=models.TextField(default=''),
        ),
    ]
